server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: myApp
    

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: myApp


